added cheatsheet to README
JaydevSR/intro-git-github-iiserb pull request #3
Opened 2023-01-24 10:50 UTC by hritikb

2023-01-24 10:53 UTC, hritikb commented
I have skipped some advanced commands. Let me know if I need to add or change something.

2023-01-24 11:22 UTC, JaydevSR requested changes
General formatting Changes

2023-01-24 11:22 UTC, JaydevSR commented on README.md
>  ## Apendix
```suggestion

```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
>  ### Cheatsheet of git commands
```suggestion
## Cheatsheet of git commands
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +#### For setup and initialization
```suggestion
### For setup and initialization
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +#### Branching and merging
```suggestion
### Branching and merging
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +#### Tracking path changes
```suggestion
### Tracking path changes
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +#### Sharing and updating
```suggestion
### Sharing and updating
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +#### Rewrite history
```suggestion
### Rewrite history
```

2023-01-24 11:22 UTC, JaydevSR commented on README.md
> +**git init**: initialize an existing directory as a Git repository<br>
```suggestion
**`git init`**: initialize an existing directory as a Git repository<br>
```

Do this for all the commands

2023-01-24 11:24 UTC, JaydevSR commented
@hritikb You can commit my suggestion as a batch from the files tab.

2023-01-24 11:27 UTC, JaydevSR commented on README.md
> +**git merge \[alias\]/\[branch\]**: merge a remote branch into your current branch to bring it up to date<br>
```suggestion
**git merge \[alias\]/ \[branch\]**: merge a remote branch into your current branch to bring it up to date<br>
```

2023-01-24 17:45 UTC, hritikb reviewed
Done

2023-01-25 06:52 UTC, JaydevSR approved these changes

2023-01-25 06:52 UTC, merged